# ***Linear Regression Using Pytorch***



### ***Training Data*** 
The Training Data can be represented using 2 matrices: inputs and targets, each with one row per observation, and one column per veriable.


In [1]:
import numpy as np 
import torch

In [8]:
#Input(Temp, Rainfall, Humidity)
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]], dtype='float32')

# Target (apples ,oranges in tons)
target = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [9]:
# Convert inputs and targets  to tensor
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)
print(inputs)
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
# Weight and bias 
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
w,b

(tensor([[ 1.5117, -0.2759,  0.9890],
         [-1.7500, -0.2394,  2.5041]], requires_grad=True),
 tensor([0.9611, 0.0190], requires_grad=True))

> @ represents matrix multiplication in PyTorch and the .t is for transpose

In [14]:
def model(x):
    return x @ w.t() + b

In [15]:
preds = model(inputs)
print(preds)

tensor([[135.3612, -36.0899],
        [177.5480, -20.0302],
        [152.8758, -39.0656],
        [179.8894, -96.1185],
        [148.0164,  31.5785]], grad_fn=<AddBackward0>)


In [16]:
# Compare with targets 
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
diff = preds-target
torch.sum(diff*diff)/diff.numel()

tensor(12459.5830, grad_fn=<DivBackward0>)

## ***Loss Function*** 
Before improve our model we need to know how well our model is performing using loss function. Here we are using MSE loss function.


In [23]:
def MSE(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()


In [24]:
loss = MSE(preds,target)
print(loss)

tensor(12459.5830, grad_fn=<DivBackward0>)


### **Compute Gradients**


In [25]:
# Compute gradients 
loss.backward()

In [26]:
#Gradients of Weights 
print(w)
print(w.grad)

tensor([[ 1.5117, -0.2759,  0.9890],
        [-1.7500, -0.2394,  2.5041]], requires_grad=True)
tensor([[  7347.4575,   5892.7217,   4109.8921],
        [-10667.6377, -10986.4053,  -6666.4980]])


In [27]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [28]:
preds = model(inputs)
print(preds)


tensor([[135.3612, -36.0899],
        [177.5480, -20.0302],
        [152.8758, -39.0656],
        [179.8894, -96.1185],
        [148.0164,  31.5785]], grad_fn=<AddBackward0>)


In [29]:
loss = MSE(preds, target)
print(loss)

tensor(12459.5830, grad_fn=<DivBackward0>)


In [30]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  7347.4575,   5892.7217,   4109.8921],
        [-10667.6377, -10986.4053,  -6666.4980]])
tensor([  82.5382, -123.9451])


In [31]:
# Adjust Weights and bais. 
with torch.no_grad():
    w -=w.grad* 1e-5
    b -=b.grad* 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [32]:
print(w)
print(b)

tensor([[ 1.4383, -0.3348,  0.9479],
        [-1.6433, -0.1295,  2.5707]], requires_grad=True)
tensor([0.9603, 0.0203], requires_grad=True)


In [33]:
preds = model(inputs)
loss = MSE(preds,target)
print(loss)

tensor(8956.5605, grad_fn=<DivBackward0>)


In [56]:
# Train for multiple epochs
for i in range (2000):
    preds = model(inputs)
    loss = MSE(preds,target)
    loss.backward()
    with torch.no_grad():
        w -=w.grad* 1e-5
        b -=b.grad* 1e-5
        w.grad.zero_()
        b.grad.zero_()



In [57]:
# Calculate Loss
preds = model(inputs)
loss = MSE(preds,target)
print(loss)

tensor(0.5306, grad_fn=<DivBackward0>)


In [58]:
preds 

tensor([[ 57.3217,  70.3111],
        [ 82.1089, 100.6691],
        [118.6671, 132.9575],
        [ 21.0617,  37.0149],
        [101.9459, 119.1387]], grad_fn=<AddBackward0>)

In [59]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [70]:
a = np.array([[91,88,64]], dtype='float32')
a = torch.from_numpy(a)
a

tensor([[91., 88., 64.]])

In [72]:
preds = model(a)
preds

tensor([[ 82.1089, 100.6691]], grad_fn=<AddBackward0>)

In [73]:
import torch .nn as nn 

In [74]:
#Input(Temp, Rainfall, Humidity)
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70],[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70],[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]], dtype='float32')

# Target (apples ,oranges in tons)
target = np.array([[56,70],[81,101],[119,133],[22,37],[103,119],[56,70],[81,101],[119,133],[22,37],[103,119],[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [75]:
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)


In [76]:
inputs,target

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

## Dataset and DataLoader

In [83]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs,target)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [84]:
from torch.utils.data import DataLoader
#Define data loader
batch_size = 5
train_dl = DataLoader(train_ds,batch_size, shuffle=True)

In [86]:
for xb,yb in train_dl:
    print("Batch")
    print(xb)
    print(yb)
    break

Batch
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 81., 101.],
        [119., 133.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [87]:
# NN.Linear 

model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3948,  0.5062,  0.2729],
        [-0.3147, -0.5427, -0.4544]], requires_grad=True)
Parameter containing:
tensor([0.1273, 0.4724], requires_grad=True)


In [90]:
# .parameters contains the weights and baises 
list(model.parameters())

[Parameter containing:
 tensor([[-0.3948,  0.5062,  0.2729],
         [-0.3147, -0.5427, -0.4544]], requires_grad=True),
 Parameter containing:
 tensor([0.1273, 0.4724], requires_grad=True)]

In [91]:
preds = model(inputs)
preds

tensor([[  16.9613,  -78.4009],
        [  26.2173, -105.0045],
        [  49.4452, -125.9843],
        [  -8.2740,  -71.7759],
        [  40.5897, -105.1490],
        [  16.9613,  -78.4009],
        [  26.2173, -105.0045],
        [  49.4452, -125.9843],
        [  -8.2740,  -71.7759],
        [  40.5897, -105.1490],
        [  16.9613,  -78.4009],
        [  26.2173, -105.0045],
        [  49.4452, -125.9843],
        [  -8.2740,  -71.7759],
        [  40.5897, -105.1490]], grad_fn=<AddmmBackward0>)

In [92]:
# Import loss function manually we can use built-in loss function mse_loss 
# Import nn.functonal 
import torch.nn.functional as F 
loss_fn = F.mse_loss


In [94]:
loss = loss_fn(model(inputs),target)
loss

tensor(20778.3125, grad_fn=<MseLossBackward0>)

In [95]:
# Defining Optimizers 
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [96]:
def fit(num_epochs, model, loss_fn, opt,train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            preds =model(xb)
            loss = loss_fn(preds,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if(epoch+1)% 10 == 0:
            print("Epoch [{}/{}], Loss:{:.4f}".format(epoch+1, num_epochs,loss))

In [122]:
fit(400,model,loss_fn,opt,train_dl)

Epoch [10/400], Loss:0.6013
Epoch [20/400], Loss:0.6337
Epoch [30/400], Loss:0.4871
Epoch [40/400], Loss:0.4525
Epoch [50/400], Loss:0.5273
Epoch [60/400], Loss:0.5247
Epoch [70/400], Loss:0.6207
Epoch [80/400], Loss:0.6819
Epoch [90/400], Loss:0.5322
Epoch [100/400], Loss:0.5618
Epoch [110/400], Loss:0.4999
Epoch [120/400], Loss:0.4348
Epoch [130/400], Loss:0.5297
Epoch [140/400], Loss:0.5599
Epoch [150/400], Loss:0.6161
Epoch [160/400], Loss:0.6372
Epoch [170/400], Loss:0.5868
Epoch [180/400], Loss:0.5992
Epoch [190/400], Loss:0.4542
Epoch [200/400], Loss:0.7211
Epoch [210/400], Loss:0.5456
Epoch [220/400], Loss:0.4635
Epoch [230/400], Loss:0.6017
Epoch [240/400], Loss:0.7133
Epoch [250/400], Loss:0.5194
Epoch [260/400], Loss:0.4701
Epoch [270/400], Loss:0.6949
Epoch [280/400], Loss:0.5605
Epoch [290/400], Loss:0.6367
Epoch [300/400], Loss:0.3897
Epoch [310/400], Loss:0.5609
Epoch [320/400], Loss:0.5627
Epoch [330/400], Loss:0.5584
Epoch [340/400], Loss:0.5644
Epoch [350/400], Loss:0

In [123]:
preds = model(inputs)
print(preds[:5])
print(target[:5])

tensor([[ 57.2019,  70.3894],
        [ 82.2145, 100.6213],
        [118.7195, 132.9453],
        [ 21.0892,  37.0065],
        [101.9466, 119.1516]], grad_fn=<SliceBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
