# ***Deep Leaning first File***

## Pytorch Basics

In [41]:
import torch 

### ***Tensor*** 
At its core, pytorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array.

In [42]:
t1 = torch.tensor(4.)
t1

tensor(4.)

<mark style="background-color: lightgray">4.</mark> is a shorthand for <mark style="background-color: lightgray">4.0</mark> . it is used to indicate to Python that you want to create a floating point number. 

We can verify this by checking <mark style="background-color: lightgray">dtype</mark> attribute of our tensor.

In [43]:
t1.dtype

torch.float32

Let's try to creating slightly more complex tensor

In [44]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [45]:
# Matrix 
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [46]:
# 3D Array 
t4 =torch.tensor([[[11,12,13],[13,14,15], [16,17,19],[11,22,33]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15],
         [16, 17, 19],
         [11, 22, 33]]])

Tensor can have any number of dimensions, and differnet lenghts along each dimension. We can inspect the length along each dimension using <mark style="background-color: lightgray">**.shape**</mark> property of a tensor.

In [47]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [48]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [49]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [50]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15],
         [16, 17, 19],
         [11, 22, 33]]])


torch.Size([1, 4, 3])

## **Tensor operations and Gradients**
We can combine tensors with the usal arthmetic operations. Let's look an example

In [51]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [52]:
# Arithmetic Operations 
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, **y** is a tensor with the value **3 * 4 + 5 = 17**. What makes Pytorch Special is that we can automatically compute the derivative of **y** w.r.t the tensor that have **required_grad** set **True** i.e. w and b. To computer the derivatives, we can call the **.backward** method on our result **y**.

In [53]:
# Compute Derivatives
y.backward()

The derivatives of **y** is stored in **.grad** property of the respective tensor.

In [54]:
# Dispalying Gradients
print("dy/dx : ",x.grad)
print("dy/dw : ",w.grad)
print("dy/db : ",b.grad)

dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


# **Interoperability with Numpy**
Numpy is a popular open source library used for mathmetical and scientific computing in Python.

It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries. 

In [55]:
import numpy as np 
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a Pytorch tensor using <mark style="background-color: lightgray">**torch.from_numpy**</mark>.

In [56]:
# Convert the numpy array to a tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [57]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [58]:
# Convert a torch tensor to a numpy array 
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [59]:
z.dtype

dtype('float64')